server:
  port: 8083 # 端口

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata_amount?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  cloud:
    # Nacos 作为注册中心的配置项
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    alibaba:
      seata:
        # 自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group

feign:
  hystrix:
    enabled: false
mybatis:
  mapper-locations: classpath*:mapper/*.xml