server:
  port: 8761

spring:
  application:
    name: eurka-server

eureka:
  instance:
    hostname: localhost
#    通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/