
server:
  port: 8762

spring:
  application:
    name: service-hi

#  指定zipkin server的地址
  zipkin:
    base-url: http://localhost:9411


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/