server:
  port: 8888

spring:
  application:
    name: config-server
#  如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写，本例子是公开仓库，放心使用
  cloud:
    config:
      server:
        git:
#          配置git仓库地址
          uri: https://github.com/xiaogc123/SpringcloudConfig.git
#          配置仓库路径
          searchPaths: respo
#          访问git仓库的用户名
        username:
#          访问git仓库的用户密码
        password:
#          配置仓库的分支
#      label: master


